const AUTOMATION_CATEGORY_DEFS = [
  {
    categoryId: "summary",
    title: "요약 집계",
    description: "부서, 항목, 상태 등 기준별 건수·합계·평균을 집계합니다.",
    internalOnly: true,
    priority: 900,
    recipeTypes: [
      "group_summary",
      "group_sum",
      "group_avg",
      "group_count",
      "category_count",
      "status_count",
      "groupAggregate",
      "multiAggregate",
      "pipelineCombine",
    ],
  },
  {
    categoryId: "trend",
    title: "추이 분석",
    description: "월별·연도별 변화, 누적합계, 성장률을 분석합니다.",
    internalOnly: true,
    priority: 850,
    recipeTypes: [
      "time_trend",
      "time_sum",
      "time_avg",
      "time_count",
      "time_growth",
      "cumulative_sum",
      "wide_time_trend",
      "cumulativeSum",
      "rollingAverage",
      "growthRate",
    ],
  },
  {
    categoryId: "ranking",
    title: "순위 / TOP 분석",
    description: "상위·하위 항목을 확인합니다.",
    internalOnly: true,
    priority: 800,
    recipeTypes: ["top_bottom", "list"],
  },
  {
    categoryId: "composition",
    title: "구성비 분석",
    description: "항목별 금액·건수 비중과 구성비를 계산합니다.",
    internalOnly: true,
    priority: 760,
    recipeTypes: ["composition_ratio"],
  },
  {
    categoryId: "cross_summary",
    title: "교차 분석",
    description: "두 기준을 교차하여 건수와 합계를 요약합니다.",
    internalOnly: true,
    priority: 720,
    recipeTypes: ["cross_count", "cross_sum", "pivot"],
  },
];

module.exports = {
  AUTOMATION_CATEGORY_DEFS,
};
