const {
  TEMPLATE_DOMAINS,
  IMPLEMENTATION_LEVELS,
  enrichTemplateDefinition,
  getTemplateDomainDefinitions,
  getImplementationLevelDefinitions,
} = require("../config/templateDomainConfig");

const RAW_BUSINESS_TEMPLATE_DEFS = [
  {
    templateId: "sales_report",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.CUSTOM,
    preferredRecipeTypes: [
      "time_sum",
      "time_growth",
      "cumulative_sum",
      "group_sum",
      "composition_ratio",
      "top_bottom",
      "wide_time_trend",
    ],
    templateTags: ["매출", "판매", "수량", "구성비", "기간추이"],
    title: "매출 분석 보고서",
    description:
      "기간별 매출, 증감률, 누적 매출, 구성비, 상위 항목, 수량, 평균 판매금액을 보고서 형태로 생성합니다.",
    requiredAnyRecipeTypes: [
      "time_trend",
      "time_sum",
      "time_growth",
      "cumulative_sum",
      "group_summary",
      "group_sum",
      "composition_ratio",
      "top_bottom",
      "wide_time_trend",
    ],
    requiredAnyHeaderHints: [
      "매출",
      "순매출액",
      "매출금액",
      "매출구성비율",
      "매출증가율",
      "전년동월대비",
      "판매",
      "판매금액",
      "판매액",
      "판매수량",
      "수량",
      "카드매출",
      "신용카드",
      "거래액",
      "출하액",
      "면세점",
      "유통업체",
      "제품류별",
      "revenue",
      "sales",
      "transaction",
    ],
    optionalHeaderHints: [
      "연도",
      "기준년도",
      "월",
      "기준월",
      "연월",
      "기간",
      "제품",
      "제품류",
      "상품",
      "품목",
      "지역",
      "자치구",
      "업종",
      "업태",
      "채널",
      "매장",
      "점포",
      "거래처",
      "고객",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 100,
  },
  {
    templateId: "research_budget_report",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.CUSTOM,
    preferredRecipeTypes: [
      "group_sum",
      "time_sum",
      "time_growth",
      "composition_ratio",
      "top_bottom",
      "wide_time_trend",
    ],
    templateTags: ["연구비", "예산", "집행", "기관", "항목"],
    title: "연구비 집행·예산 현황",
    description:
      "연구비, 집행액, 정부출연금, 현금·현물 집행, 항목별·사업별·기관별·연도별 현황과 집행률을 보고서 형태로 생성합니다.",
    requiredAnyRecipeTypes: [
      "group_summary",
      "group_sum",
      "time_trend",
      "time_sum",
      "time_growth",
      "cumulative_sum",
      "composition_ratio",
      "top_bottom",
      "wide_time_trend",
    ],
    requiredAnyHeaderHints: [
      "연구비",
      "연구개발비",
      "총 연구비",
      "총연구비",
      "집행금액",
      "집행액",
      "현금집행금액",
      "현물집행금액",
      "정부출연금",
      "정부지원금",
      "민간부담금",
      "과제명",
      "세부과제명",
      "사업명",
      "항목명",
      "비목",
      "기관분류",
      "기관유형",
      "전문기관",
      "연구기관",
      "수행기관",
      "연구책임자",
      "RnD",
      "R&D",
      "budget",
      "grant",
      "expense",
    ],
    optionalHeaderHints: [
      "예산",
      "예산년도",
      "진행년도",
      "집행년도",
      "연도",
      "년도",
      "현금",
      "현물",
      "세목",
      "집행항목",
      "이용항목",
      "프로그램",
      "내역사업명",
      "주관기관",
      "과제고유번호",
      "과제번호",
      "당해년도 연구기간 시작일",
      "당해년도 연구기간 종료일",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 95,
  },
  {
    templateId: "hr_monthly_report",
    domain: TEMPLATE_DOMAINS.HR,
    implementationLevel: IMPLEMENTATION_LEVELS.CUSTOM,
    preferredRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "group_summary",
      "time_count",
      "composition_ratio",
      "top_bottom",
    ],
    templateTags: ["인사", "명단", "상태", "부서", "직급", "입퇴사"],
    title: "월간 인사 보고서",
    description:
      "임직원 명단, 재직/퇴사 상태, 부서·직급·고용형태별 인원 구성, 입퇴사 증감, 평가등급, 교육이수, 급여·연봉 요약을 보고서 형태로 생성합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "group_summary",
      "group_avg",
      "time_count",
      "time_trend",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "부서",
      "부서명",
      "소속",
      "조직",
      "팀",
      "직급",
      "직위",
      "직책",
      "직무",
      "재직",
      "재직상태",
      "근무상태",
      "상태",
      "퇴사",
      "휴직",
      "고용형태",
      "근무형태",
      "계약형태",
      "성명",
      "이름",
      "직원명",
      "사원명",
      "사번",
      "입사",
      "입사일",
      "채용일",
      "퇴사일",
      "연봉",
      "급여",
      "월급",
      "인건비",
      "평가등급",
      "성과평가",
      "교육이수",
      "employee",
      "department",
      "position",
      "status",
      "salary",
      "hire date",
    ],
    optionalHeaderHints: [
      "직원",
      "사원",
      "임직원",
      "구성원",
      "인사",
      "인원",
      "headcount",
      "평가",
      "고과",
      "성과",
      "조직",
      "본부",
      "근무",
      "재직기간",
      "근속",
      "나이",
      "연령",
      "교육",
      "수료",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 90,
  },
  {
    templateId: "purchase_analysis_report",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: [
      "group_sum",
      "time_sum",
      "composition_ratio",
      "top_bottom",
    ],
    templateTags: ["매입", "구매", "거래처", "품목", "월별"],
    title: "매입·구매 분석 보고서",
    description: "거래처·품목·월별 매입/구매 금액과 상위 거래처를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "매입",
      "구매",
      "발주",
      "거래처",
      "업체",
      "공급사",
      "품목",
      "상품",
      "금액",
      "단가",
      "purchase",
      "vendor",
      "supplier",
    ],
    optionalHeaderHints: [
      "월",
      "연월",
      "일자",
      "날짜",
      "부서",
      "담당자",
      "수량",
      "검수",
      "상태",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 68,
  },
  {
    templateId: "sales_quantity_analysis",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: [
      "time_sum",
      "group_sum",
      "cumulative_sum",
      "top_bottom",
    ],
    templateTags: ["판매수량", "수량", "상품", "누적", "기간추이"],
    title: "판매수량 분석",
    description:
      "상품·품목별 판매수량, 월별 판매량, 누적 판매량과 상위/하위 품목을 요약합니다.",
    requiredAnyRecipeTypes: [
      "time_sum",
      "group_sum",
      "cumulative_sum",
      "top_bottom",
      "wide_time_trend",
    ],
    requiredAnyHeaderHints: [
      "판매수량",
      "매출수량",
      "수량",
      "판매량",
      "주문수",
      "거래건수",
      "상품",
      "제품",
      "품목",
      "quantity",
      "qty",
      "count",
    ],
    optionalHeaderHints: [
      "월",
      "연월",
      "연도",
      "기간",
      "지역",
      "지점",
      "채널",
      "매장",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 66,
  },
  {
    templateId: "branch_performance_report",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "group_avg", "top_bottom"],
    templateTags: ["지점", "매장", "실적", "순위", "평균"],
    title: "지점별 실적 분석",
    description: "지점·매장별 매출/실적 합계, 평균 실적, 순위를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_summary",
      "group_sum",
      "group_avg",
      "top_bottom",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "지점",
      "매장",
      "점포",
      "영업점",
      "센터",
      "실적",
      "매출",
      "판매",
      "branch",
      "store",
      "shop",
    ],
    optionalHeaderHints: [
      "담당자",
      "지역",
      "권역",
      "월",
      "연월",
      "목표",
      "달성",
      "금액",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 64,
  },
  {
    templateId: "regional_performance_report",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: [
      "group_sum",
      "time_growth",
      "composition_ratio",
      "top_bottom",
    ],
    templateTags: ["지역", "권역", "매출", "구성비", "성장률"],
    title: "지역별 실적 분석",
    description:
      "지역·권역별 매출/실적 합계, 구성비, 성장률과 상위 지역을 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "time_growth",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "지역",
      "권역",
      "시도",
      "시군구",
      "자치구",
      "구",
      "광역시",
      "도",
      "매출",
      "실적",
      "region",
      "area",
    ],
    optionalHeaderHints: [
      "월",
      "연월",
      "연도",
      "상품",
      "업종",
      "거래액",
      "금액",
      "건수",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 63,
  },
  {
    templateId: "product_sales_analysis",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "composition_ratio", "top_bottom"],
    templateTags: ["상품", "제품", "품목", "매출", "상위"],
    title: "상품·품목별 매출 분석",
    description:
      "상품군·제품·품목별 매출 합계, 구성비, 상위/하위 항목을 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_summary",
      "group_sum",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "상품",
      "제품",
      "품목",
      "품명",
      "제품류",
      "제품군",
      "브랜드",
      "카테고리",
      "매출",
      "판매",
      "product",
      "item",
      "sku",
    ],
    optionalHeaderHints: ["월", "연월", "지역", "지점", "수량", "금액", "단가"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 65,
  },
  {
    templateId: "account_sales_analysis",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "composition_ratio", "top_bottom"],
    templateTags: ["거래처", "고객", "매출", "집중도", "상위"],
    title: "거래처·고객별 매출 분석",
    description:
      "거래처·고객별 매출 합계, 매출 집중도, 상위 거래처를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "group_summary",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "거래처",
      "고객",
      "회원",
      "업체",
      "계정",
      "client",
      "customer",
      "account",
      "매출",
      "판매",
      "금액",
    ],
    optionalHeaderHints: [
      "담당자",
      "지역",
      "월",
      "연월",
      "상품",
      "품목",
      "채널",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 62,
  },
  {
    templateId: "project_expense_settlement_summary",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "time_sum", "composition_ratio"],
    templateTags: ["사업비", "정산", "비목", "증빙", "지출"],
    title: "사업비 정산 요약",
    description: "비목·세목별 사용액, 월별 지출, 증빙/정산 상태를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "사업비",
      "정산",
      "비목",
      "세목",
      "증빙",
      "사용액",
      "지출",
      "집행",
      "금액",
      "expense",
      "settlement",
    ],
    optionalHeaderHints: [
      "월",
      "일자",
      "날짜",
      "부서",
      "사업명",
      "상태",
      "승인",
      "카드",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 67,
  },
  {
    templateId: "corporate_card_usage_report",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "time_sum", "top_bottom"],
    templateTags: ["법인카드", "카드", "가맹점", "사용자", "금액"],
    title: "법인카드 사용 내역",
    description:
      "사용자·가맹점·비목별 카드 사용금액, 월별 사용 추이, 상위 사용처를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "composition_ratio",
      "top_bottom",
      "category_count",
    ],
    requiredAnyHeaderHints: [
      "법인카드",
      "카드",
      "승인금액",
      "사용금액",
      "가맹점",
      "사용처",
      "사용자",
      "이용자",
      "비목",
      "card",
      "merchant",
    ],
    optionalHeaderHints: [
      "승인일",
      "사용일",
      "월",
      "부서",
      "항목",
      "업종",
      "상태",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 66,
  },
  {
    templateId: "travel_expense_settlement_analysis",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "time_sum", "composition_ratio"],
    templateTags: ["출장", "여비", "정산", "지역", "출장자"],
    title: "출장비 정산 분석",
    description: "출장자·지역·월별 출장비/여비 금액과 정산 상태를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "출장",
      "여비",
      "출장비",
      "교통비",
      "숙박비",
      "일비",
      "출장자",
      "지역",
      "목적지",
      "정산",
      "travel",
      "trip",
    ],
    optionalHeaderHints: [
      "부서",
      "일자",
      "날짜",
      "월",
      "금액",
      "상태",
      "증빙",
      "승인",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 64,
  },
  {
    templateId: "meeting_expense_usage_report",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "time_sum", "category_count"],
    templateTags: ["회의비", "회의", "참석자", "월별", "금액"],
    title: "회의비 사용 현황",
    description:
      "회의별 금액, 참석자 수, 월별 회의비 사용 추이와 유형별 사용액을 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "회의비",
      "회의",
      "간담회",
      "참석자",
      "참석인원",
      "식대",
      "다과",
      "사용금액",
      "금액",
      "meeting",
    ],
    optionalHeaderHints: ["일자", "날짜", "월", "부서", "목적", "장소", "상태"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 61,
  },
  {
    templateId: "purchase_inspection_status",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["group_sum", "category_count", "status_count"],
    templateTags: ["구매", "검수", "물품", "업체", "상태"],
    title: "구매·검수 현황",
    description: "물품·업체별 구매금액, 검수 상태, 처리 건수를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "category_count",
      "status_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "구매",
      "검수",
      "물품",
      "품목",
      "업체",
      "공급사",
      "발주",
      "납품",
      "상태",
      "금액",
      "inspection",
      "procurement",
    ],
    optionalHeaderHints: [
      "일자",
      "날짜",
      "부서",
      "담당자",
      "수량",
      "단가",
      "완료",
      "미완료",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 63,
  },
  {
    templateId: "service_contract_execution_status",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["group_sum", "category_count", "status_count"],
    templateTags: ["용역", "계약", "업체", "집행", "상태"],
    title: "용역 계약 집행 현황",
    description:
      "계약·업체별 금액, 계약/집행 상태, 월별 집행 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "category_count",
      "status_count",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "용역",
      "계약",
      "계약금액",
      "집행금액",
      "업체",
      "계약상대자",
      "상태",
      "검수",
      "완료",
      "contract",
      "service",
    ],
    optionalHeaderHints: [
      "계약일",
      "시작일",
      "종료일",
      "월",
      "부서",
      "담당자",
      "금액",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 60,
  },
  {
    templateId: "monthly_expense_report",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["time_sum", "group_sum", "top_bottom"],
    templateTags: ["월간", "지출", "비용", "카테고리", "상위"],
    title: "월간 지출 리포트",
    description: "월별 지출, 카테고리별 지출, 상위 지출 항목을 요약합니다.",
    requiredAnyRecipeTypes: [
      "time_sum",
      "group_sum",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "지출",
      "비용",
      "사용금액",
      "결제금액",
      "금액",
      "카테고리",
      "항목",
      "비목",
      "expense",
      "cost",
      "amount",
    ],
    optionalHeaderHints: [
      "월",
      "연월",
      "일자",
      "날짜",
      "부서",
      "사용자",
      "거래처",
      "가맹점",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 65,
  },
  {
    templateId: "employee_roster_status",
    domain: TEMPLATE_DOMAINS.HR,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["직원", "구성원", "명단", "부서", "상태"],
    title: "직원·구성원 명단 현황",
    description:
      "직원/구성원 명단의 부서별 인원, 직급별 인원, 상태별 인원과 입사일 기준 추이를 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "time_count",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "직원",
      "사원",
      "임직원",
      "구성원",
      "명단",
      "성명",
      "이름",
      "부서",
      "직급",
      "상태",
      "입사일",
      "employee",
      "roster",
    ],
    optionalHeaderHints: [
      "사번",
      "소속",
      "조직",
      "직위",
      "고용형태",
      "재직",
      "퇴사",
      "연봉",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 64,
  },
  {
    templateId: "recruitment_applicant_management",
    domain: TEMPLATE_DOMAINS.HR,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "group_avg"],
    templateTags: ["채용", "지원자", "전형", "합격", "평가"],
    title: "채용 지원자 관리",
    description:
      "전형별 지원자 수, 합격/불합격 상태, 지원 분야별 집계를 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "group_avg",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "채용",
      "지원자",
      "지원분야",
      "전형",
      "면접",
      "합격",
      "불합격",
      "평가",
      "점수",
      "applicant",
      "recruit",
    ],
    optionalHeaderHints: [
      "성명",
      "이름",
      "상태",
      "단계",
      "부서",
      "직무",
      "지원일",
      "일자",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 59,
  },
  {
    templateId: "research_participant_status",
    domain: TEMPLATE_DOMAINS.HR,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "time_count", "group_summary"],
    templateTags: ["참여연구원", "역할", "소속", "참여기간", "인건비"],
    title: "참여연구원 현황",
    description:
      "참여연구원 역할별·소속별 인원, 참여기간, 인건비/지급액 요약을 생성합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "group_summary",
      "time_count",
    ],
    requiredAnyHeaderHints: [
      "참여연구원",
      "연구원",
      "참여자",
      "역할",
      "소속",
      "기관",
      "참여기간",
      "시작일",
      "종료일",
      "인건비",
      "지급액",
      "researcher",
      "participant",
    ],
    optionalHeaderHints: [
      "성명",
      "이름",
      "부서",
      "상태",
      "참여율",
      "월",
      "금액",
      "과제",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 58,
  },
  {
    templateId: "purchase_order_status",
    domain: TEMPLATE_DOMAINS.INVENTORY,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["group_sum", "category_count", "status_count"],
    templateTags: ["발주", "업체", "품목", "상태", "금액"],
    title: "발주 현황",
    description:
      "업체별 발주액, 품목별 발주 수량/금액, 발주 상태별 건수를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "category_count",
      "status_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "발주",
      "주문",
      "구매요청",
      "업체",
      "공급사",
      "품목",
      "수량",
      "금액",
      "상태",
      "order",
      "purchase order",
    ],
    optionalHeaderHints: [
      "납기",
      "입고",
      "검수",
      "일자",
      "월",
      "부서",
      "담당자",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 55,
  },
  {
    templateId: "asset_equipment_management",
    domain: TEMPLATE_DOMAINS.INVENTORY,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "group_sum", "status_count"],
    templateTags: ["장비", "비품", "자산", "부서", "상태"],
    title: "장비·비품 관리",
    description:
      "자산·장비·비품별 상태, 부서별 보유 현황, 구매금액을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "group_sum",
      "status_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "장비",
      "비품",
      "자산",
      "물품",
      "기자재",
      "구매금액",
      "취득금액",
      "부서",
      "보유",
      "상태",
      "asset",
      "equipment",
    ],
    optionalHeaderHints: [
      "관리번호",
      "구매일",
      "취득일",
      "위치",
      "담당자",
      "수량",
      "금액",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 54,
  },
  {
    templateId: "customer_inquiry_analysis",
    domain: TEMPLATE_DOMAINS.CUSTOMER,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["고객", "문의", "CS", "상태", "유형"],
    title: "고객 문의 분석",
    description:
      "문의 유형, 처리 상태, 월별 문의 건수와 담당자/채널별 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "고객",
      "문의",
      "상담",
      "CS",
      "VOC",
      "처리상태",
      "유형",
      "카테고리",
      "접수일",
      "customer",
      "inquiry",
      "ticket",
    ],
    optionalHeaderHints: [
      "담당자",
      "채널",
      "처리일",
      "상태",
      "월",
      "지역",
      "불만",
      "요청",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 57,
  },
  {
    templateId: "event_applicant_status",
    domain: TEMPLATE_DOMAINS.OPERATION,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["행사", "신청자", "참석", "취소", "소속"],
    title: "행사 신청자 현황",
    description:
      "행사 신청/참석/취소 상태, 소속별 인원, 회차·월별 신청자 수를 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "행사",
      "신청자",
      "참석자",
      "참석",
      "신청",
      "취소",
      "소속",
      "기관",
      "회차",
      "event",
      "attendee",
      "applicant",
    ],
    optionalHeaderHints: [
      "성명",
      "이름",
      "상태",
      "등록일",
      "신청일",
      "월",
      "부서",
      "연락처",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 56,
  },
  {
    templateId: "education_completion_status",
    domain: TEMPLATE_DOMAINS.OPERATION,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["교육", "이수", "수료", "미이수", "상태"],
    title: "교육 이수 현황",
    description:
      "교육 과정별 이수/미이수 상태, 부서별 이수율, 월별 교육 참여 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "교육",
      "과정",
      "이수",
      "수료",
      "미이수",
      "교육명",
      "수강",
      "참여자",
      "상태",
      "completion",
      "training",
    ],
    optionalHeaderHints: [
      "부서",
      "성명",
      "이름",
      "이수일",
      "수료일",
      "월",
      "점수",
      "기관",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 55,
  },
  {
    templateId: "maintenance_request_status",
    domain: TEMPLATE_DOMAINS.OPERATION,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["유지보수", "요청", "처리", "장애", "상태"],
    title: "유지보수 요청 처리 현황",
    description:
      "유지보수 요청 유형, 처리 상태, 담당자별 처리 건수와 지연 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "유지보수",
      "보수",
      "수리",
      "장애",
      "고장",
      "요청",
      "처리상태",
      "접수일",
      "maintenance",
      "repair",
      "issue",
    ],
    optionalHeaderHints: [
      "담당자",
      "부서",
      "처리일",
      "완료일",
      "장비",
      "위치",
      "우선순위",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 54,
  },
  {
    templateId: "safety_inspection_status",
    domain: TEMPLATE_DOMAINS.OPERATION,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["안전", "점검", "위험", "조치", "상태"],
    title: "안전점검 현황",
    description:
      "점검 대상별 안전점검 결과, 조치 상태, 위험 등급별 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "안전",
      "점검",
      "검사",
      "위험",
      "위험등급",
      "조치",
      "점검결과",
      "상태",
      "safety",
      "inspection",
    ],
    optionalHeaderHints: [
      "점검일",
      "부서",
      "위치",
      "담당자",
      "대상",
      "완료",
      "미조치",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 53,
  },
  {
    templateId: "delivery_logistics_status",
    domain: TEMPLATE_DOMAINS.OPERATION,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["배송", "물류", "출고", "도착", "상태"],
    title: "배송·물류 처리 현황",
    description:
      "배송 상태, 출고/도착 일자, 지역·운송사별 처리 건수와 지연 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "배송",
      "물류",
      "출고",
      "입고",
      "도착",
      "운송",
      "택배",
      "송장",
      "배송상태",
      "delivery",
      "logistics",
    ],
    optionalHeaderHints: [
      "지역",
      "운송사",
      "출고일",
      "도착일",
      "지연",
      "수량",
      "품목",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 52,
  },
  {
    templateId: "project_progress_status",
    domain: TEMPLATE_DOMAINS.PROJECT,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["프로젝트", "과제", "진행", "완료", "상태"],
    title: "프로젝트 진행 현황",
    description:
      "프로젝트·과제별 진행 상태, 담당 조직, 시작/종료 일정과 완료율을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "group_summary",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "프로젝트",
      "과제",
      "사업",
      "진행상태",
      "완료",
      "진행률",
      "마일스톤",
      "담당자",
      "project",
      "milestone",
    ],
    optionalHeaderHints: [
      "시작일",
      "종료일",
      "부서",
      "PM",
      "목표",
      "실적",
      "예산",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 56,
  },
  {
    templateId: "task_issue_tracking_report",
    domain: TEMPLATE_DOMAINS.OPERATION,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["업무", "이슈", "태스크", "담당자", "상태"],
    title: "업무 이슈 처리 현황",
    description:
      "업무/이슈별 처리 상태, 담당자별 처리 건수, 지연·완료 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "업무",
      "이슈",
      "태스크",
      "작업",
      "요청",
      "처리상태",
      "담당자",
      "완료",
      "issue",
      "task",
    ],
    optionalHeaderHints: [
      "등록일",
      "마감일",
      "처리일",
      "우선순위",
      "부서",
      "분류",
      "지연",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 53,
  },
  {
    templateId: "grant_application_status",
    domain: TEMPLATE_DOMAINS.PROJECT,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "group_sum"],
    templateTags: ["지원사업", "신청", "선정", "과제", "상태"],
    title: "지원사업 신청·선정 현황",
    description:
      "지원사업 신청자/기관별 신청 상태, 선정 결과, 신청 금액과 분야별 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "group_sum",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "지원사업",
      "신청",
      "선정",
      "접수",
      "평가",
      "신청금액",
      "지원금",
      "기관",
      "과제",
      "grant",
      "application",
    ],
    optionalHeaderHints: [
      "신청일",
      "분야",
      "상태",
      "결과",
      "사업명",
      "담당자",
      "금액",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 54,
  },
  {
    templateId: "attendance_check_report",
    domain: TEMPLATE_DOMAINS.OPERATION,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["출석", "참석", "결석", "행사", "상태"],
    title: "출석·참석 현황",
    description:
      "교육·행사·회의별 참석/결석 상태, 소속별 참석률과 날짜별 참석 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "출석",
      "참석",
      "결석",
      "불참",
      "참가",
      "참석여부",
      "출석상태",
      "attendance",
      "attend",
    ],
    optionalHeaderHints: [
      "일자",
      "날짜",
      "성명",
      "소속",
      "부서",
      "행사",
      "교육",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 51,
  },
  {
    templateId: "contract_payment_schedule_report",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["time_sum", "group_sum", "category_count"],
    templateTags: ["계약", "대금", "지급", "일정", "금액"],
    title: "계약 대금 지급 일정",
    description:
      "계약별 지급 예정액, 지급일정, 업체별 지급 금액과 지급 상태를 요약합니다.",
    requiredAnyRecipeTypes: [
      "time_sum",
      "group_sum",
      "category_count",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "계약",
      "대금",
      "지급",
      "지급예정",
      "지급일",
      "계약금액",
      "업체",
      "거래처",
      "payment",
      "contract",
    ],
    optionalHeaderHints: [
      "상태",
      "월",
      "일자",
      "부서",
      "담당자",
      "잔액",
      "세금계산서",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 57,
  },
  {
    templateId: "vendor_performance_report",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "category_count", "top_bottom"],
    templateTags: ["업체", "거래처", "실적", "금액", "평가"],
    title: "업체·거래처 실적 분석",
    description:
      "업체/거래처별 거래금액, 건수, 평가등급, 상위 거래처를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "업체",
      "거래처",
      "공급사",
      "계약상대자",
      "거래금액",
      "구매금액",
      "평가등급",
      "실적",
      "vendor",
      "supplier",
    ],
    optionalHeaderHints: ["월", "일자", "부서", "품목", "계약", "상태", "건수"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 56,
  },
  {
    templateId: "revenue_cost_profit_report",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "time_sum", "top_bottom"],
    templateTags: ["매출", "비용", "이익", "손익", "마진"],
    title: "매출·비용·손익 분석",
    description:
      "매출액, 비용, 이익, 마진율을 기간별·상품별·부서별로 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "time_growth",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "매출",
      "비용",
      "원가",
      "이익",
      "손익",
      "마진",
      "수익",
      "영업이익",
      "profit",
      "margin",
    ],
    optionalHeaderHints: [
      "월",
      "연월",
      "상품",
      "부서",
      "채널",
      "지역",
      "고객",
      "금액",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 63,
  },
  {
    templateId: "public_monthly_statistics_report",
    domain: TEMPLATE_DOMAINS.PUBLIC_DATA,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["time_sum", "wide_time_trend", "group_sum"],
    templateTags: ["공공데이터", "통계", "월별", "지표", "추이"],
    title: "공공 월별 통계 분석",
    description:
      "공공데이터 월별 지표, 지역·분류별 통계, 가로형 기간 컬럼 추이를 요약합니다.",
    requiredAnyRecipeTypes: [
      "time_sum",
      "time_trend",
      "wide_time_trend",
      "group_sum",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "통계",
      "지표",
      "월별",
      "연월",
      "기준월",
      "지역",
      "공공데이터",
      "데이터",
      "statistics",
      "indicator",
    ],
    optionalHeaderHints: [
      "시도",
      "시군구",
      "분류",
      "항목",
      "값",
      "수치",
      "합계",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 57,
  },
  {
    templateId: "kpi_performance_dashboard",
    domain: TEMPLATE_DOMAINS.PROJECT,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "time_sum", "composition_ratio"],
    templateTags: ["KPI", "성과", "목표", "실적", "달성률"],
    title: "KPI 성과 대시보드",
    description:
      "KPI별 목표·실적·달성률, 조직별 성과와 기간별 추이를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "group_avg",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "KPI",
      "성과",
      "목표",
      "실적",
      "달성률",
      "달성율",
      "지표명",
      "평가",
      "performance",
      "target",
    ],
    optionalHeaderHints: [
      "월",
      "분기",
      "부서",
      "담당자",
      "단위",
      "가중치",
      "등급",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 58,
  },
  {
    templateId: "quality_defect_analysis",
    domain: TEMPLATE_DOMAINS.OPERATION,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["품질", "불량", "결함", "조치", "상태"],
    title: "품질·불량 분석",
    description:
      "품질 불량 유형, 발생/조치 상태, 원인별 건수와 월별 발생 추이를 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "품질",
      "불량",
      "결함",
      "하자",
      "조치",
      "원인",
      "발생일",
      "처리상태",
      "quality",
      "defect",
    ],
    optionalHeaderHints: [
      "제품",
      "공정",
      "담당자",
      "부서",
      "수량",
      "등급",
      "완료일",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 52,
  },
  {
    templateId: "energy_usage_report",
    domain: TEMPLATE_DOMAINS.PUBLIC_DATA,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["time_sum", "group_sum", "composition_ratio"],
    templateTags: ["에너지", "전력", "사용량", "절감", "통계"],
    title: "에너지 사용량 분석",
    description:
      "에너지 사용량, 절감량, 비용, 시설·기간별 사용 추이를 요약합니다.",
    requiredAnyRecipeTypes: [
      "time_sum",
      "group_sum",
      "time_growth",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "에너지",
      "전력",
      "전기",
      "가스",
      "사용량",
      "절감",
      "소비량",
      "투자비",
      "회수기간",
      "energy",
    ],
    optionalHeaderHints: ["월", "연도", "시설", "지역", "비용", "진단", "결과"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 54,
  },
  {
    templateId: "survey_satisfaction_analysis",
    domain: TEMPLATE_DOMAINS.SURVEY,
    implementationLevel: IMPLEMENTATION_LEVELS.SURVEY_SCORE,
    preferredRecipeTypes: [
      "group_avg",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    templateTags: ["설문", "만족도", "평점", "문항", "응답"],
    title: "설문 만족도 분석",
    description:
      "문항별 만족도 평균, 응답 분포, 긍정률, 응답자·유형별 점수를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_avg",
      "group_count",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "설문",
      "만족도",
      "평점",
      "점수",
      "문항",
      "응답",
      "추천",
      "score",
      "rating",
      "satisfaction",
    ],
    optionalHeaderHints: [
      "응답자",
      "부서",
      "소속",
      "유형",
      "구분",
      "응답일",
      "의견",
    ],
    scoreHeaderHints: ["만족도", "평점", "점수", "추천점수", "score", "rating"],
    questionHeaderHints: ["문항", "질문", "평가항목", "설문항목"],
    categoryHeaderHints: ["구분", "유형", "프로그램", "서비스", "채널"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 55,
  },
  {
    templateId: "education_feedback_report",
    domain: TEMPLATE_DOMAINS.SURVEY,
    implementationLevel: IMPLEMENTATION_LEVELS.SURVEY_SCORE,
    preferredRecipeTypes: [
      "group_avg",
      "category_count",
      "time_avg",
      "top_bottom",
    ],
    templateTags: ["교육", "강의", "만족도", "피드백", "평가"],
    title: "교육 피드백 분석",
    description:
      "교육과정·강사·문항별 만족도와 수강생 피드백 점수를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_avg",
      "category_count",
      "time_avg",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "교육",
      "강의",
      "과정",
      "강사",
      "수강",
      "만족도",
      "평가",
      "점수",
      "feedback",
      "course",
    ],
    optionalHeaderHints: [
      "교육일",
      "수강생",
      "부서",
      "문항",
      "의견",
      "개선사항",
    ],
    scoreHeaderHints: ["만족도", "평가점수", "강의평점", "이해도", "추천점수"],
    questionHeaderHints: ["문항", "평가항목", "질문"],
    categoryHeaderHints: ["교육과정", "과정", "강사", "교육명"],
    dateHeaderHints: ["교육일", "응답일", "평가일"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 54,
  },
  {
    templateId: "event_satisfaction_report",
    domain: TEMPLATE_DOMAINS.SURVEY,
    implementationLevel: IMPLEMENTATION_LEVELS.SURVEY_SCORE,
    preferredRecipeTypes: [
      "group_avg",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    templateTags: ["행사", "만족도", "참석자", "피드백", "설문"],
    title: "행사 만족도 분석",
    description:
      "행사·세션·참석자 유형별 만족도와 추천 의향, 개선 의견을 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_avg",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "행사",
      "세션",
      "참석",
      "만족도",
      "추천",
      "평점",
      "설문",
      "event",
      "session",
    ],
    optionalHeaderHints: ["행사일", "참석자", "소속", "구분", "의견", "개선"],
    scoreHeaderHints: ["만족도", "추천점수", "행사평점", "운영평가", "score"],
    categoryHeaderHints: ["행사명", "세션", "참석자구분", "소속"],
    dateHeaderHints: ["행사일", "응답일"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 53,
  },
  {
    templateId: "course_evaluation_report",
    domain: TEMPLATE_DOMAINS.SURVEY,
    implementationLevel: IMPLEMENTATION_LEVELS.SURVEY_SCORE,
    preferredRecipeTypes: [
      "group_avg",
      "time_avg",
      "category_count",
      "top_bottom",
    ],
    templateTags: ["강좌", "수업", "강의평가", "교육평가", "점수"],
    title: "강좌·수업 평가 분석",
    description: "강좌, 강사, 학습 항목별 평가 점수와 응답 분포를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_avg",
      "time_avg",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "강좌",
      "수업",
      "강의",
      "강사",
      "학습",
      "평가",
      "점수",
      "평점",
      "course",
      "class",
    ],
    optionalHeaderHints: ["학기", "교육일", "수강생", "문항", "의견"],
    scoreHeaderHints: ["평가점수", "강의평점", "만족도", "이해도", "난이도"],
    questionHeaderHints: ["평가항목", "문항", "질문"],
    categoryHeaderHints: ["강좌", "수업", "강사", "학기"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 52,
  },
  {
    templateId: "customer_satisfaction_report",
    domain: TEMPLATE_DOMAINS.SURVEY,
    implementationLevel: IMPLEMENTATION_LEVELS.SURVEY_SCORE,
    preferredRecipeTypes: [
      "group_avg",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    templateTags: ["고객", "CS", "만족도", "NPS", "서비스"],
    title: "고객 만족도 분석",
    description:
      "고객 유형, 서비스, 채널별 만족도와 NPS/추천 점수를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_avg",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "고객",
      "만족도",
      "서비스",
      "NPS",
      "추천",
      "평점",
      "채널",
      "customer",
      "satisfaction",
    ],
    optionalHeaderHints: [
      "고객유형",
      "서비스",
      "채널",
      "응답일",
      "의견",
      "지점",
    ],
    scoreHeaderHints: ["만족도", "추천점수", "NPS", "서비스평점", "score"],
    categoryHeaderHints: ["고객유형", "서비스", "채널", "지점"],
    dateHeaderHints: ["응답일", "조사일"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 55,
  },
  {
    templateId: "internal_survey_score_report",
    domain: TEMPLATE_DOMAINS.SURVEY,
    implementationLevel: IMPLEMENTATION_LEVELS.SURVEY_SCORE,
    preferredRecipeTypes: [
      "group_avg",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    templateTags: ["내부설문", "직원", "조직", "만족도", "평가"],
    title: "내부 설문 점수 분석",
    description:
      "직원·부서·조직 단위의 내부 설문 점수, 긍정률, 문항별 평균을 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_avg",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "직원",
      "부서",
      "조직",
      "내부설문",
      "만족도",
      "평가",
      "점수",
      "응답",
      "employee",
      "survey",
    ],
    optionalHeaderHints: ["응답자", "부서", "직급", "문항", "응답일", "의견"],
    scoreHeaderHints: ["만족도", "평가점수", "몰입도", "추천점수", "점수"],
    departmentHeaderHints: ["부서", "팀", "소속", "조직"],
    questionHeaderHints: ["문항", "질문", "평가항목"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 51,
  },
];

const BUSINESS_TEMPLATE_DEFS = RAW_BUSINESS_TEMPLATE_DEFS.map(
  enrichTemplateDefinition,
);

function getBusinessTemplateDefinitions() {
  return BUSINESS_TEMPLATE_DEFS;
}

function findBusinessTemplateDefinition(templateId = "") {
  return (
    BUSINESS_TEMPLATE_DEFS.find((def) => def.templateId === templateId) || null
  );
}

module.exports = {
  BUSINESS_TEMPLATE_DEFS,
  getBusinessTemplateDefinitions,
  findBusinessTemplateDefinition,
  getTemplateDomainDefinitions,
  getImplementationLevelDefinitions,
};
