const {
  TEMPLATE_DOMAINS,
  IMPLEMENTATION_LEVELS,
  enrichTemplateDefinition,
  getTemplateDomainDefinitions,
  getImplementationLevelDefinitions,
} = require("../config/templateDomainConfig");

const RAW_BUSINESS_TEMPLATE_DEFS = [
  {
    templateId: "sales_report",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.CUSTOM,
    preferredRecipeTypes: [
      "time_sum",
      "time_growth",
      "cumulative_sum",
      "group_sum",
      "composition_ratio",
      "top_bottom",
      "wide_time_trend",
    ],
    templateTags: ["매출", "판매", "수량", "구성비", "기간추이"],
    title: "매출 분석 보고서",
    description:
      "기간별 매출, 증감률, 누적 매출, 구성비, 상위 항목, 수량, 평균 판매금액을 보고서 형태로 생성합니다.",
    requiredAnyRecipeTypes: [
      "time_trend",
      "time_sum",
      "time_growth",
      "cumulative_sum",
      "group_summary",
      "group_sum",
      "composition_ratio",
      "top_bottom",
      "wide_time_trend",
    ],
    requiredAnyHeaderHints: [
      "매출",
      "순매출액",
      "매출금액",
      "매출구성비율",
      "매출증가율",
      "전년동월대비",
      "판매",
      "판매금액",
      "판매액",
      "판매수량",
      "수량",
      "카드매출",
      "신용카드",
      "거래액",
      "출하액",
      "면세점",
      "유통업체",
      "제품류별",
      "revenue",
      "sales",
      "transaction",
    ],
    optionalHeaderHints: [
      "연도",
      "기준년도",
      "월",
      "기준월",
      "연월",
      "기간",
      "제품",
      "제품류",
      "상품",
      "품목",
      "지역",
      "자치구",
      "업종",
      "업태",
      "채널",
      "매장",
      "점포",
      "거래처",
      "고객",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 100,
  },
  {
    templateId: "research_budget_report",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.CUSTOM,
    preferredRecipeTypes: [
      "group_sum",
      "time_sum",
      "time_growth",
      "composition_ratio",
      "top_bottom",
      "wide_time_trend",
    ],
    templateTags: ["연구비", "예산", "집행", "기관", "항목"],
    title: "연구비 집행·예산 현황",
    description:
      "연구비, 집행액, 정부출연금, 현금·현물 집행, 항목별·사업별·기관별·연도별 현황과 집행률을 보고서 형태로 생성합니다.",
    requiredAnyRecipeTypes: [
      "group_summary",
      "group_sum",
      "time_trend",
      "time_sum",
      "time_growth",
      "cumulative_sum",
      "composition_ratio",
      "top_bottom",
      "wide_time_trend",
    ],
    requiredAnyHeaderHints: [
      "연구비",
      "연구개발비",
      "총 연구비",
      "총연구비",
      "집행금액",
      "집행액",
      "현금집행금액",
      "현물집행금액",
      "정부출연금",
      "정부지원금",
      "민간부담금",
      "과제명",
      "세부과제명",
      "사업명",
      "항목명",
      "비목",
      "기관분류",
      "기관유형",
      "전문기관",
      "연구기관",
      "수행기관",
      "연구책임자",
      "RnD",
      "R&D",
      "budget",
      "grant",
      "expense",
    ],
    optionalHeaderHints: [
      "예산",
      "예산년도",
      "진행년도",
      "집행년도",
      "연도",
      "년도",
      "현금",
      "현물",
      "세목",
      "집행항목",
      "이용항목",
      "프로그램",
      "내역사업명",
      "주관기관",
      "과제고유번호",
      "과제번호",
      "당해년도 연구기간 시작일",
      "당해년도 연구기간 종료일",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 95,
  },
  {
    templateId: "hr_monthly_report",
    domain: TEMPLATE_DOMAINS.HR,
    implementationLevel: IMPLEMENTATION_LEVELS.CUSTOM,
    preferredRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "group_summary",
      "time_count",
      "composition_ratio",
      "top_bottom",
    ],
    templateTags: ["인사", "명단", "상태", "부서", "직급", "입퇴사"],
    title: "월간 인사 보고서",
    description:
      "임직원 명단, 재직/퇴사 상태, 부서·직급·고용형태별 인원 구성, 입퇴사 증감, 평가등급, 교육이수, 급여·연봉 요약을 보고서 형태로 생성합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "group_summary",
      "group_avg",
      "time_count",
      "time_trend",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "부서",
      "부서명",
      "소속",
      "조직",
      "팀",
      "직급",
      "직위",
      "직책",
      "직무",
      "재직",
      "재직상태",
      "근무상태",
      "상태",
      "퇴사",
      "휴직",
      "고용형태",
      "근무형태",
      "계약형태",
      "성명",
      "이름",
      "직원명",
      "사원명",
      "사번",
      "입사",
      "입사일",
      "채용일",
      "퇴사일",
      "연봉",
      "급여",
      "월급",
      "인건비",
      "평가등급",
      "성과평가",
      "교육이수",
      "employee",
      "department",
      "position",
      "status",
      "salary",
      "hire date",
    ],
    optionalHeaderHints: [
      "직원",
      "사원",
      "임직원",
      "구성원",
      "인사",
      "인원",
      "headcount",
      "평가",
      "고과",
      "성과",
      "조직",
      "본부",
      "근무",
      "재직기간",
      "근속",
      "나이",
      "연령",
      "교육",
      "수료",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 90,
  },
  {
    templateId: "purchase_analysis_report",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: [
      "group_sum",
      "time_sum",
      "composition_ratio",
      "top_bottom",
    ],
    templateTags: ["매입", "구매", "거래처", "품목", "월별"],
    title: "매입·구매 분석 보고서",
    description: "거래처·품목·월별 매입/구매 금액과 상위 거래처를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "매입",
      "구매",
      "발주",
      "거래처",
      "업체",
      "공급사",
      "품목",
      "상품",
      "금액",
      "단가",
      "purchase",
      "vendor",
      "supplier",
    ],
    optionalHeaderHints: [
      "월",
      "연월",
      "일자",
      "날짜",
      "부서",
      "담당자",
      "수량",
      "검수",
      "상태",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 68,
  },
  {
    templateId: "sales_quantity_analysis",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: [
      "time_sum",
      "group_sum",
      "cumulative_sum",
      "top_bottom",
    ],
    templateTags: ["판매수량", "수량", "상품", "누적", "기간추이"],
    title: "판매수량 분석",
    description:
      "상품·품목별 판매수량, 월별 판매량, 누적 판매량과 상위/하위 품목을 요약합니다.",
    requiredAnyRecipeTypes: [
      "time_sum",
      "group_sum",
      "cumulative_sum",
      "top_bottom",
      "wide_time_trend",
    ],
    requiredAnyHeaderHints: [
      "판매수량",
      "매출수량",
      "수량",
      "판매량",
      "주문수",
      "거래건수",
      "상품",
      "제품",
      "품목",
      "quantity",
      "qty",
      "count",
    ],
    optionalHeaderHints: [
      "월",
      "연월",
      "연도",
      "기간",
      "지역",
      "지점",
      "채널",
      "매장",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 66,
  },
  {
    templateId: "branch_performance_report",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "group_avg", "top_bottom"],
    templateTags: ["지점", "매장", "실적", "순위", "평균"],
    title: "지점별 실적 분석",
    description: "지점·매장별 매출/실적 합계, 평균 실적, 순위를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_summary",
      "group_sum",
      "group_avg",
      "top_bottom",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "지점",
      "매장",
      "점포",
      "영업점",
      "센터",
      "실적",
      "매출",
      "판매",
      "branch",
      "store",
      "shop",
    ],
    optionalHeaderHints: [
      "담당자",
      "지역",
      "권역",
      "월",
      "연월",
      "목표",
      "달성",
      "금액",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 64,
  },
  {
    templateId: "regional_performance_report",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: [
      "group_sum",
      "time_growth",
      "composition_ratio",
      "top_bottom",
    ],
    templateTags: ["지역", "권역", "매출", "구성비", "성장률"],
    title: "지역별 실적 분석",
    description:
      "지역·권역별 매출/실적 합계, 구성비, 성장률과 상위 지역을 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "time_growth",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "지역",
      "권역",
      "시도",
      "시군구",
      "자치구",
      "구",
      "광역시",
      "도",
      "매출",
      "실적",
      "region",
      "area",
    ],
    optionalHeaderHints: [
      "월",
      "연월",
      "연도",
      "상품",
      "업종",
      "거래액",
      "금액",
      "건수",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 63,
  },
  {
    templateId: "product_sales_analysis",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "composition_ratio", "top_bottom"],
    templateTags: ["상품", "제품", "품목", "매출", "상위"],
    title: "상품·품목별 매출 분석",
    description:
      "상품군·제품·품목별 매출 합계, 구성비, 상위/하위 항목을 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_summary",
      "group_sum",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "상품",
      "제품",
      "품목",
      "품명",
      "제품류",
      "제품군",
      "브랜드",
      "카테고리",
      "매출",
      "판매",
      "product",
      "item",
      "sku",
    ],
    optionalHeaderHints: ["월", "연월", "지역", "지점", "수량", "금액", "단가"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 65,
  },
  {
    templateId: "account_sales_analysis",
    domain: TEMPLATE_DOMAINS.SALES,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "composition_ratio", "top_bottom"],
    templateTags: ["거래처", "고객", "매출", "집중도", "상위"],
    title: "거래처·고객별 매출 분석",
    description:
      "거래처·고객별 매출 합계, 매출 집중도, 상위 거래처를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "group_summary",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "거래처",
      "고객",
      "회원",
      "업체",
      "계정",
      "client",
      "customer",
      "account",
      "매출",
      "판매",
      "금액",
    ],
    optionalHeaderHints: [
      "담당자",
      "지역",
      "월",
      "연월",
      "상품",
      "품목",
      "채널",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 62,
  },
  {
    templateId: "project_expense_settlement_summary",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "time_sum", "composition_ratio"],
    templateTags: ["사업비", "정산", "비목", "증빙", "지출"],
    title: "사업비 정산 요약",
    description: "비목·세목별 사용액, 월별 지출, 증빙/정산 상태를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "사업비",
      "정산",
      "비목",
      "세목",
      "증빙",
      "사용액",
      "지출",
      "집행",
      "금액",
      "expense",
      "settlement",
    ],
    optionalHeaderHints: [
      "월",
      "일자",
      "날짜",
      "부서",
      "사업명",
      "상태",
      "승인",
      "카드",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 67,
  },
  {
    templateId: "corporate_card_usage_report",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "time_sum", "top_bottom"],
    templateTags: ["법인카드", "카드", "가맹점", "사용자", "금액"],
    title: "법인카드 사용 내역",
    description:
      "사용자·가맹점·비목별 카드 사용금액, 월별 사용 추이, 상위 사용처를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "composition_ratio",
      "top_bottom",
      "category_count",
    ],
    requiredAnyHeaderHints: [
      "법인카드",
      "카드",
      "승인금액",
      "사용금액",
      "가맹점",
      "사용처",
      "사용자",
      "이용자",
      "비목",
      "card",
      "merchant",
    ],
    optionalHeaderHints: [
      "승인일",
      "사용일",
      "월",
      "부서",
      "항목",
      "업종",
      "상태",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 66,
  },
  {
    templateId: "travel_expense_settlement_analysis",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "time_sum", "composition_ratio"],
    templateTags: ["출장", "여비", "정산", "지역", "출장자"],
    title: "출장비 정산 분석",
    description: "출장자·지역·월별 출장비/여비 금액과 정산 상태를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "출장",
      "여비",
      "출장비",
      "교통비",
      "숙박비",
      "일비",
      "출장자",
      "지역",
      "목적지",
      "정산",
      "travel",
      "trip",
    ],
    optionalHeaderHints: [
      "부서",
      "일자",
      "날짜",
      "월",
      "금액",
      "상태",
      "증빙",
      "승인",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 64,
  },
  {
    templateId: "meeting_expense_usage_report",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["group_sum", "time_sum", "category_count"],
    templateTags: ["회의비", "회의", "참석자", "월별", "금액"],
    title: "회의비 사용 현황",
    description:
      "회의별 금액, 참석자 수, 월별 회의비 사용 추이와 유형별 사용액을 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "category_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "회의비",
      "회의",
      "간담회",
      "참석자",
      "참석인원",
      "식대",
      "다과",
      "사용금액",
      "금액",
      "meeting",
    ],
    optionalHeaderHints: ["일자", "날짜", "월", "부서", "목적", "장소", "상태"],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 61,
  },
  {
    templateId: "purchase_inspection_status",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["group_sum", "category_count", "status_count"],
    templateTags: ["구매", "검수", "물품", "업체", "상태"],
    title: "구매·검수 현황",
    description: "물품·업체별 구매금액, 검수 상태, 처리 건수를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "category_count",
      "status_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "구매",
      "검수",
      "물품",
      "품목",
      "업체",
      "공급사",
      "발주",
      "납품",
      "상태",
      "금액",
      "inspection",
      "procurement",
    ],
    optionalHeaderHints: [
      "일자",
      "날짜",
      "부서",
      "담당자",
      "수량",
      "단가",
      "완료",
      "미완료",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 63,
  },
  {
    templateId: "service_contract_execution_status",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["group_sum", "category_count", "status_count"],
    templateTags: ["용역", "계약", "업체", "집행", "상태"],
    title: "용역 계약 집행 현황",
    description:
      "계약·업체별 금액, 계약/집행 상태, 월별 집행 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "time_sum",
      "category_count",
      "status_count",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "용역",
      "계약",
      "계약금액",
      "집행금액",
      "업체",
      "계약상대자",
      "상태",
      "검수",
      "완료",
      "contract",
      "service",
    ],
    optionalHeaderHints: [
      "계약일",
      "시작일",
      "종료일",
      "월",
      "부서",
      "담당자",
      "금액",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 60,
  },
  {
    templateId: "monthly_expense_report",
    domain: TEMPLATE_DOMAINS.BUDGET,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["time_sum", "group_sum", "top_bottom"],
    templateTags: ["월간", "지출", "비용", "카테고리", "상위"],
    title: "월간 지출 리포트",
    description: "월별 지출, 카테고리별 지출, 상위 지출 항목을 요약합니다.",
    requiredAnyRecipeTypes: [
      "time_sum",
      "group_sum",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "지출",
      "비용",
      "사용금액",
      "결제금액",
      "금액",
      "카테고리",
      "항목",
      "비목",
      "expense",
      "cost",
      "amount",
    ],
    optionalHeaderHints: [
      "월",
      "연월",
      "일자",
      "날짜",
      "부서",
      "사용자",
      "거래처",
      "가맹점",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 65,
  },
  {
    templateId: "employee_roster_status",
    domain: TEMPLATE_DOMAINS.HR,
    implementationLevel: IMPLEMENTATION_LEVELS.DEFINITION_ONLY,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["직원", "구성원", "명단", "부서", "상태"],
    title: "직원·구성원 명단 현황",
    description:
      "직원/구성원 명단의 부서별 인원, 직급별 인원, 상태별 인원과 입사일 기준 추이를 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "time_count",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "직원",
      "사원",
      "임직원",
      "구성원",
      "명단",
      "성명",
      "이름",
      "부서",
      "직급",
      "상태",
      "입사일",
      "employee",
      "roster",
    ],
    optionalHeaderHints: [
      "사번",
      "소속",
      "조직",
      "직위",
      "고용형태",
      "재직",
      "퇴사",
      "연봉",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 64,
  },
  {
    templateId: "recruitment_applicant_management",
    domain: TEMPLATE_DOMAINS.HR,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "group_avg"],
    templateTags: ["채용", "지원자", "전형", "합격", "평가"],
    title: "채용 지원자 관리",
    description:
      "전형별 지원자 수, 합격/불합격 상태, 지원 분야별 집계를 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "group_avg",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "채용",
      "지원자",
      "지원분야",
      "전형",
      "면접",
      "합격",
      "불합격",
      "평가",
      "점수",
      "applicant",
      "recruit",
    ],
    optionalHeaderHints: [
      "성명",
      "이름",
      "상태",
      "단계",
      "부서",
      "직무",
      "지원일",
      "일자",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 59,
  },
  {
    templateId: "research_participant_status",
    domain: TEMPLATE_DOMAINS.HR,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "time_count", "group_summary"],
    templateTags: ["참여연구원", "역할", "소속", "참여기간", "인건비"],
    title: "참여연구원 현황",
    description:
      "참여연구원 역할별·소속별 인원, 참여기간, 인건비/지급액 요약을 생성합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "group_summary",
      "time_count",
    ],
    requiredAnyHeaderHints: [
      "참여연구원",
      "연구원",
      "참여자",
      "역할",
      "소속",
      "기관",
      "참여기간",
      "시작일",
      "종료일",
      "인건비",
      "지급액",
      "researcher",
      "participant",
    ],
    optionalHeaderHints: [
      "성명",
      "이름",
      "부서",
      "상태",
      "참여율",
      "월",
      "금액",
      "과제",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 58,
  },
  {
    templateId: "purchase_order_status",
    domain: TEMPLATE_DOMAINS.INVENTORY,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["group_sum", "category_count", "status_count"],
    templateTags: ["발주", "업체", "품목", "상태", "금액"],
    title: "발주 현황",
    description:
      "업체별 발주액, 품목별 발주 수량/금액, 발주 상태별 건수를 요약합니다.",
    requiredAnyRecipeTypes: [
      "group_sum",
      "category_count",
      "status_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "발주",
      "주문",
      "구매요청",
      "업체",
      "공급사",
      "품목",
      "수량",
      "금액",
      "상태",
      "order",
      "purchase order",
    ],
    optionalHeaderHints: [
      "납기",
      "입고",
      "검수",
      "일자",
      "월",
      "부서",
      "담당자",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 55,
  },
  {
    templateId: "asset_equipment_management",
    domain: TEMPLATE_DOMAINS.INVENTORY,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "group_sum", "status_count"],
    templateTags: ["장비", "비품", "자산", "부서", "상태"],
    title: "장비·비품 관리",
    description:
      "자산·장비·비품별 상태, 부서별 보유 현황, 구매금액을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "group_sum",
      "status_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "장비",
      "비품",
      "자산",
      "물품",
      "기자재",
      "구매금액",
      "취득금액",
      "부서",
      "보유",
      "상태",
      "asset",
      "equipment",
    ],
    optionalHeaderHints: [
      "관리번호",
      "구매일",
      "취득일",
      "위치",
      "담당자",
      "수량",
      "금액",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 54,
  },
  {
    templateId: "customer_inquiry_analysis",
    domain: TEMPLATE_DOMAINS.CUSTOMER,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["고객", "문의", "CS", "상태", "유형"],
    title: "고객 문의 분석",
    description:
      "문의 유형, 처리 상태, 월별 문의 건수와 담당자/채널별 현황을 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "고객",
      "문의",
      "상담",
      "CS",
      "VOC",
      "처리상태",
      "유형",
      "카테고리",
      "접수일",
      "customer",
      "inquiry",
      "ticket",
    ],
    optionalHeaderHints: [
      "담당자",
      "채널",
      "처리일",
      "상태",
      "월",
      "지역",
      "불만",
      "요청",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 57,
  },
  {
    templateId: "event_applicant_status",
    domain: TEMPLATE_DOMAINS.OPERATION,
    implementationLevel: IMPLEMENTATION_LEVELS.STATUS_RATE,
    preferredRecipeTypes: ["category_count", "status_count", "time_count"],
    templateTags: ["행사", "신청자", "참석", "취소", "소속"],
    title: "행사 신청자 현황",
    description:
      "행사 신청/참석/취소 상태, 소속별 인원, 회차·월별 신청자 수를 요약합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "time_count",
      "composition_ratio",
    ],
    requiredAnyHeaderHints: [
      "행사",
      "신청자",
      "참석자",
      "참석",
      "신청",
      "취소",
      "소속",
      "기관",
      "회차",
      "event",
      "attendee",
      "applicant",
    ],
    optionalHeaderHints: [
      "성명",
      "이름",
      "상태",
      "등록일",
      "신청일",
      "월",
      "부서",
      "연락처",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 56,
  },
];

const BUSINESS_TEMPLATE_DEFS = RAW_BUSINESS_TEMPLATE_DEFS.map(
  enrichTemplateDefinition,
);

function getBusinessTemplateDefinitions() {
  return BUSINESS_TEMPLATE_DEFS;
}

function findBusinessTemplateDefinition(templateId = "") {
  return (
    BUSINESS_TEMPLATE_DEFS.find((def) => def.templateId === templateId) || null
  );
}

module.exports = {
  BUSINESS_TEMPLATE_DEFS,
  getBusinessTemplateDefinitions,
  findBusinessTemplateDefinition,
  getTemplateDomainDefinitions,
  getImplementationLevelDefinitions,
};
