const BUSINESS_TEMPLATE_DEFS = [
  {
    templateId: "sales_report",
    title: "매출 분석 보고서",
    description:
      "기간별 매출, 증감률, 누적 매출, 구성비, 상위 항목, 수량, 평균 판매금액을 보고서 형태로 생성합니다.",
    requiredAnyRecipeTypes: [
      "time_trend",
      "time_sum",
      "time_growth",
      "cumulative_sum",
      "group_summary",
      "group_sum",
      "composition_ratio",
      "top_bottom",
      "wide_time_trend",
    ],
    requiredAnyHeaderHints: [
      "매출",
      "순매출액",
      "매출금액",
      "매출구성비율",
      "매출증가율",
      "전년동월대비",
      "판매",
      "판매금액",
      "판매액",
      "판매수량",
      "수량",
      "카드매출",
      "신용카드",
      "거래액",
      "출하액",
      "면세점",
      "유통업체",
      "제품류별",
      "revenue",
      "sales",
      "transaction",
    ],
    optionalHeaderHints: [
      "연도",
      "기준년도",
      "월",
      "기준월",
      "연월",
      "기간",
      "제품",
      "제품류",
      "상품",
      "품목",
      "지역",
      "자치구",
      "업종",
      "업태",
      "채널",
      "매장",
      "점포",
      "거래처",
      "고객",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 100,
  },
  {
    templateId: "research_budget_report",
    title: "연구비 집행·예산 현황",
    description:
      "연구비, 집행액, 정부출연금, 현금·현물 집행, 항목별·사업별·기관별·연도별 현황과 집행률을 보고서 형태로 생성합니다.",
    requiredAnyRecipeTypes: [
      "group_summary",
      "group_sum",
      "time_trend",
      "time_sum",
      "time_growth",
      "cumulative_sum",
      "composition_ratio",
      "top_bottom",
      "wide_time_trend",
    ],
    requiredAnyHeaderHints: [
      "연구비",
      "연구개발비",
      "총 연구비",
      "총연구비",
      "집행금액",
      "집행액",
      "현금집행금액",
      "현물집행금액",
      "정부출연금",
      "정부지원금",
      "민간부담금",
      "과제명",
      "세부과제명",
      "사업명",
      "항목명",
      "비목",
      "기관분류",
      "기관유형",
      "전문기관",
      "연구기관",
      "수행기관",
      "연구책임자",
      "RnD",
      "R&D",
      "budget",
      "grant",
      "expense",
    ],
    optionalHeaderHints: [
      "예산",
      "예산년도",
      "진행년도",
      "집행년도",
      "연도",
      "년도",
      "현금",
      "현물",
      "세목",
      "집행항목",
      "이용항목",
      "프로그램",
      "내역사업명",
      "주관기관",
      "과제고유번호",
      "과제번호",
      "당해년도 연구기간 시작일",
      "당해년도 연구기간 종료일",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 95,
  },
  {
    templateId: "hr_monthly_report",
    title: "월간 인사 보고서",
    description:
      "임직원 명단, 재직/퇴사 상태, 부서·직급·고용형태별 인원 구성, 입퇴사 증감, 평가등급, 교육이수, 급여·연봉 요약을 보고서 형태로 생성합니다.",
    requiredAnyRecipeTypes: [
      "category_count",
      "status_count",
      "group_count",
      "group_summary",
      "group_avg",
      "time_count",
      "time_trend",
      "composition_ratio",
      "top_bottom",
    ],
    requiredAnyHeaderHints: [
      "부서",
      "부서명",
      "소속",
      "조직",
      "팀",
      "직급",
      "직위",
      "직책",
      "직무",
      "재직",
      "재직상태",
      "근무상태",
      "상태",
      "퇴사",
      "휴직",
      "고용형태",
      "근무형태",
      "계약형태",
      "성명",
      "이름",
      "직원명",
      "사원명",
      "사번",
      "입사",
      "입사일",
      "채용일",
      "퇴사일",
      "연봉",
      "급여",
      "월급",
      "인건비",
      "평가등급",
      "성과평가",
      "교육이수",
      "employee",
      "department",
      "position",
      "status",
      "salary",
      "hire date",
    ],
    optionalHeaderHints: [
      "직원",
      "사원",
      "임직원",
      "구성원",
      "인사",
      "인원",
      "headcount",
      "평가",
      "고과",
      "성과",
      "조직",
      "본부",
      "근무",
      "재직기간",
      "근속",
      "나이",
      "연령",
      "교육",
      "수료",
    ],
    outputTypes: ["summarySheet", "analysisReport", "ppt"],
    priority: 90,
  },
];

function getBusinessTemplateDefinitions() {
  return BUSINESS_TEMPLATE_DEFS;
}

function findBusinessTemplateDefinition(templateId = "") {
  return (
    BUSINESS_TEMPLATE_DEFS.find((def) => def.templateId === templateId) || null
  );
}

module.exports = {
  BUSINESS_TEMPLATE_DEFS,
  getBusinessTemplateDefinitions,
  findBusinessTemplateDefinition,
};
