"use strict";
const assert=require("assert"),crypto=require("crypto"),fs=require("fs"),path=require("path");
const ROOT=path.resolve(__dirname,"..");
const manifestPath=path.join(ROOT,"PATCH_MANIFEST_PATCH15_3_2.json");
assert(fs.existsSync(manifestPath),"PATCH_MANIFEST_PATCH15_3_2.json is required");
const manifest=JSON.parse(fs.readFileSync(manifestPath,"utf8"));
assert.strictEqual(manifest.version,"query_candidate_patch15_3_2_manifest_v1");
assert.strictEqual(manifest.patch,"Real Shadow Evidence Collector & Bundle Builder");
assert(Array.isArray(manifest.files));
assert.strictEqual(manifest.fileCount,manifest.files.length);
assert(manifest.fileCount>=45);
for(const entry of manifest.files){const full=path.join(ROOT,entry.path);assert(fs.existsSync(full),`manifest file missing: ${entry.path}`);const bytes=fs.readFileSync(full);const hash=crypto.createHash("sha256").update(bytes).digest("hex");assert.strictEqual(hash,entry.sha256,`SHA-256 mismatch: ${entry.path}`);assert.strictEqual(bytes.length,entry.bytes,`byte size mismatch: ${entry.path}`);}
assert.strictEqual(manifest.collection.defaultEnabled,false);
assert.strictEqual(manifest.collection.allowlistOnly,true);
assert.strictEqual(manifest.collection.actualTrafficOnly,true);
assert.strictEqual(manifest.collection.encryption,"AES-256-GCM");
assert.strictEqual(manifest.collection.ttlDaysDefault,7);
assert.strictEqual(manifest.evidence.minimumExecutionSampleSize,30);
assert.strictEqual(manifest.evidence.minimumObservationsPerAccuracyCase,3);
assert.strictEqual(manifest.evidence.approvedActualPricingRequired,true);
assert.strictEqual(manifest.llmPolicy.mode,"SEMANTIC_PROFILER_ONLY");
assert.strictEqual(manifest.llmPolicy.plannerEscalationAllowed,false);
assert.strictEqual(manifest.guardrails.internalCanaryAutoEnabled,false);
assert.strictEqual(manifest.guardrails.productionCandidateMerge,false);
assert.strictEqual(manifest.guardrails.productionReadyAssignment,false);
assert.strictEqual(manifest.guardrails.productionRouteChanged,false);
assert.strictEqual(manifest.guardrails.promotionAuthorized,false);
assert.strictEqual(manifest.guardrails.failClosed,true);
for(const key of ["patch14_2Files","patch14_3Files","patch15_3Files"])assert(Array.isArray(manifest.supersedes[key]));
console.log("PASS query candidate patch15.3.2 manifest smoke");
