"use strict";
const assert = require("assert");
const { completeLedger } = require("./queryCandidatePatch15_3_2_BTestSupport");
const { finalizeRealShadowCaseRegistry } = require("../automation/queryCandidatePlannerRealShadowRegistryFinalization");
const { dataset, ledger } = completeLedger();
const options = { accuracyDataset: dataset, ledger, now: Date.parse("2026-08-06T05:30:00.000Z") };
const first = finalizeRealShadowCaseRegistry(options);
const second = finalizeRealShadowCaseRegistry(options);
assert.deepStrictEqual(first, second);
console.log("PASS query candidate patch15.3.2-B deterministic finalization smoke");
