"use strict";
const assert = require("assert");
const { completeSourceCatalog } = require("./queryCandidatePatch15_3_2_BTestSupport");
const { buildRealShadowFingerprintLedgerScaffold, validateRealShadowFingerprintLedger } = require("../automation/queryCandidatePlannerRealShadowRegistryFinalization");
const support = completeSourceCatalog();
const ledger = { ...buildRealShadowFingerprintLedgerScaffold(support.dataset, support.catalog), email: "private@example.com" };
const result = validateRealShadowFingerprintLedger({ accuracyDataset: support.dataset, sourceCatalog: support.catalog, ledger, requireComplete: false });
assert.strictEqual(result.valid, false);
assert(result.errors.some((item) => item.includes("forbidden field")));
console.log("PASS query candidate patch15.3.2-B privacy fail-closed smoke superseded=B.1");
