"use strict";
const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync, spawnSync } = require("child_process");
const root = fs.mkdtempSync(path.join(os.tmpdir(), "beebee-private-guard-"));
execFileSync("git", ["init", "-q"], { cwd: root });
execFileSync("git", ["config", "user.email", "qa@example.com"], { cwd: root });
execFileSync("git", ["config", "user.name", "QA"], { cwd: root });
const privateName = "queryCandidatePlannerRealShadowCaseRegistry.private.json";
fs.writeFileSync(path.join(root, privateName), "{}\n");
execFileSync("git", ["add", privateName], { cwd: root });
const script = path.resolve(__dirname, "../scripts/queryCandidatePlannerAssertRealShadowPrivateOutputsUntracked.js");
const result = spawnSync(process.execPath, [script], { cwd: root, encoding: "utf8" });
assert.strictEqual(result.status, 2);
assert(result.stderr.includes("BLOCKED staged private file"));
fs.rmSync(root, { recursive: true, force: true });
console.log("PASS query candidate patch15.3.2-B private output staging guard smoke");
