"use strict";
const assert = require("assert");
const { completeSourceCatalog, hash } = require("./queryCandidatePatch15_3_2_BTestSupport");
const { buildRealShadowFingerprintLedgerScaffold, upsertRealShadowFingerprintCapture } = require("../automation/queryCandidatePlannerRealShadowRegistryFinalization");
const support = completeSourceCatalog();
let ledger = buildRealShadowFingerprintLedgerScaffold(support.dataset, support.catalog);
const first = support.dataset.cases[0];
const second = support.dataset.cases[1];
ledger = upsertRealShadowFingerprintCapture({ accuracyDataset: support.dataset, sourceCatalog: support.catalog, ledger, sourceFilePath: support.sources.byCaseId.get(first.caseId), caseId: first.caseId, requestFingerprintSha256: hash("a"), uploadFingerprintSha256: hash("b"), captureSource: "INTERNAL_PREVIEW" }).ledger;
assert.throws(() => upsertRealShadowFingerprintCapture({ accuracyDataset: support.dataset, sourceCatalog: support.catalog, ledger, sourceFilePath: support.sources.byCaseId.get(second.caseId), caseId: second.caseId, requestFingerprintSha256: hash("a"), uploadFingerprintSha256: hash("c"), captureSource: "INTERNAL_PREVIEW" }), (error) => error.code === "REAL_SHADOW_REQUEST_FINGERPRINT_DUPLICATE");
console.log("PASS query candidate patch15.3.2-B duplicate fingerprint fail-closed smoke superseded=B.1");
