"use strict";
const assert = require("assert");
const { completeSourceCatalog } = require("./queryCandidatePatch15_3_2_BTestSupport");
const { buildRealShadowFingerprintLedgerScaffold } = require("../automation/queryCandidatePlannerRealShadowRegistryFinalization");
const support = completeSourceCatalog();
const ledger = buildRealShadowFingerprintLedgerScaffold(support.dataset, support.catalog);
assert.strictEqual(ledger.cases.length, 10);
assert.strictEqual(ledger.version, "query_candidate_planner_real_shadow_fingerprint_ledger_v2");
assert.strictEqual(ledger.legacyCapturesPreserved, false);
console.log("PASS query candidate patch15.3.2-B fingerprint ledger scaffold smoke superseded=B.1");
